name: keccak
description: pre-NIST Dart implementation of keccak used by cryptocurrencies.
version: 1.0.3
author: Rashed Mohammed <chandu.rashed@gmail.com>
homepage: https://github.com/rashedmyt/keccak

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  convert: ^3.0.1

dev_dependencies:
  test: ^1.5.1+1
